# Generated by Django 5.1.7 on 2025-04-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('model_name', models.CharField(default='facebook/bart-large-cnn', max_length=200)),
                ('summary_min_length', models.IntegerField(default=30)),
                ('summary_max_length', models.IntegerField(default=150)),
            ],
        ),
    ]
